[package]
name = "libyuv-rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.60"
authors = ["yangandmore"]
license = "MIT"
readme = "README.md"
repository = ""
homepage = ""
description = "---"
categories = ["multimedia::encoding"]
keywords = ["yuv", "rgba", "rgb"]

